

package anteikucafepos;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.*;
/**
 *
 * @author Administrator
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        SizesGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtboxProdCode = new javax.swing.JTextField();
        txtboxProdName = new javax.swing.JTextField();
        txtboxProdQuantity = new javax.swing.JSpinner();
        txtboxProdPrice = new javax.swing.JTextField();
        btnRemoveItem = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        radbtnMedium = new javax.swing.JRadioButton();
        radbtnLarge = new javax.swing.JRadioButton();
        radbtnSmall = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtboxTotal = new javax.swing.JTextField();
        txtboxTenderAmount = new javax.swing.JTextField();
        txtboxChange = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnPrintBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtboxBill = new javax.swing.JTextArea();
        btnNewTransaction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainGUI");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        jPanel1.setBackground(new java.awt.Color(102, 51, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anteiku Cafe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price");

        txtboxProdCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtboxProdCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtboxProdCodeKeyReleased(evt);
            }
        });

        txtboxProdName.setEditable(false);
        txtboxProdName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtboxProdPrice.setEditable(false);
        txtboxProdPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnRemoveItem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRemoveItem.setText("Remove");
        btnRemoveItem.setToolTipText("");
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        btnAddItem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAddItem.setText("Add");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        SizesGroup.add(radbtnMedium);
        radbtnMedium.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radbtnMedium.setForeground(new java.awt.Color(255, 255, 255));
        radbtnMedium.setText("Medium");
        radbtnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnMediumActionPerformed(evt);
            }
        });

        SizesGroup.add(radbtnLarge);
        radbtnLarge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radbtnLarge.setForeground(new java.awt.Color(255, 255, 255));
        radbtnLarge.setText("Large");
        radbtnLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnLargeActionPerformed(evt);
            }
        });

        SizesGroup.add(radbtnSmall);
        radbtnSmall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radbtnSmall.setForeground(new java.awt.Color(255, 255, 255));
        radbtnSmall.setSelected(true);
        radbtnSmall.setText("Small");
        radbtnSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radbtnSmallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtboxProdCode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtboxProdName)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtboxProdQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtboxProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radbtnSmall)
                        .addGap(36, 36, 36)
                        .addComponent(radbtnMedium)
                        .addGap(29, 29, 29)
                        .addComponent(radbtnLarge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnRemoveItem)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtboxProdCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtboxProdQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radbtnMedium)
                            .addComponent(radbtnLarge)
                            .addComponent(radbtnSmall))
                        .addGap(17, 17, 17))))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Checkout");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tender Amount");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Change");

        txtboxTotal.setEditable(false);
        txtboxTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtboxTenderAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtboxTenderAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtboxTenderAmountKeyReleased(evt);
            }
        });

        txtboxChange.setEditable(false);
        txtboxChange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Total");

        btnPrintBill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrintBill.setText("Print Bill");
        btnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillActionPerformed(evt);
            }
        });

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Size", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setResizable(false);
            tblCart.getColumnModel().getColumn(1).setResizable(false);
            tblCart.getColumnModel().getColumn(2).setResizable(false);
            tblCart.getColumnModel().getColumn(3).setResizable(false);
            tblCart.getColumnModel().getColumn(4).setResizable(false);
        }

        txtboxBill.setColumns(20);
        txtboxBill.setRows(5);
        jScrollPane2.setViewportView(txtboxBill);

        btnNewTransaction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNewTransaction.setText("New Transaction");
        btnNewTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewTransactionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtboxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(50, 50, 50))
                                    .addComponent(txtboxChange, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel8)))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(txtboxTenderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnPrintBill))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnNewTransaction)
                                .addGap(106, 106, 106))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtboxTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtboxTenderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtboxChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    ArrayList<Products> ProductItems = new ArrayList<>();
    Cart cart;
    
    public class Cart{
        private DefaultTableModel _model = (DefaultTableModel) tblCart.getModel();
        private String _transactID;
        
        public void AddItem(String ProductID, String ProductSize, int Quantity , float Total){
            for (Products i: ProductItems)
            {
                if(i.getProductId().equals(ProductID)){
                    Object[] rowData = { i.getProductId(),i.getProductName(), ProductSize, Quantity, Total * Quantity};
                    _model.addRow(rowData);
                }
            }
            CalculateTotal();
        }
        
        public void RemoveItem(){
            try{
                _model.removeRow(tblCart.getSelectedRow());
            }catch (java.lang.ArrayIndexOutOfBoundsException AIE){
                System.out.println("No items to be deleted");
            }
            CalculateTotal();
        }
        
        public void CalculateTotal(){
            float total = 0f;
            for (int i = 0; i < _model.getRowCount(); i++) {
                total = total + (Float)tblCart.getValueAt(i, 4);
            }
            txtboxTotal.setText(String.valueOf(total));
        }
        
        private String GenerateTransactID() {
            int min = 1000;
            int max = 10000000;
            int random_int = (int)Math.floor(Math.random()*(max-min+1)+min);
            return String.valueOf(random_int);
        }
        
        public void PrintBill(){
            String total = txtboxTotal.getText();
            String pay = txtboxTenderAmount.getText();
            String bal = txtboxChange.getText();
            _transactID = GenerateTransactID();

            txtboxBill.setText(txtboxBill.getText() + "******************************************************\n");
            txtboxBill.setText(txtboxBill.getText() + "           AnteikuCafe Shop Bill                                     \n");
            txtboxBill.setText(txtboxBill.getText() + "*******************************************************\n");
            txtboxBill.setText(txtboxBill.getText() + "Transaction ID : \t" + _transactID + "\n");
            txtboxBill.setText(txtboxBill.getText() + "Product \t" + "Quantity \t \n");
            for(int i = 0; i < _model.getRowCount(); i++){
                String prodname = (String)_model.getValueAt(i, 1);
                String quantity = String.valueOf((Integer)_model.getValueAt(i, 3));
                String amount = String.valueOf((Float)_model.getValueAt(i, 4)); 
                txtboxBill.setText(txtboxBill.getText() + prodname + "\t" + quantity + "\t" + amount  + "\n"  );
            }
            txtboxBill.setText(txtboxBill.getText() + "\n");     
            txtboxBill.setText(txtboxBill.getText() + "\t" + "\t" + "Subtotal :" + total + "\n");
            txtboxBill.setText(txtboxBill.getText() + "\t" + "\t" + "Tender Amount :" + pay + "\n");
            txtboxBill.setText(txtboxBill.getText() + "\t" + "\t" + "Change :" + bal + "\n");
            txtboxBill.setText(txtboxBill.getText() + "\n");
            txtboxBill.setText(txtboxBill.getText() + "*******************************************************\n");
            txtboxBill.setText(txtboxBill.getText() + "           THANK YOU COME AGIN             \n");
        }
        
    }
    
    
    private void UpdateItemView(){
        txtboxProdName.setText("");
        txtboxProdPrice.setText("");
        txtboxProdQuantity.setValue(1);
        
        for (Products i: ProductItems) {
            if(txtboxProdCode.getText().equals(i.getProductId())){
                txtboxProdName.setText(i.getProductName());
                
                float price = 0f;
                if(radbtnSmall.isSelected())
                    price = i._prices.getItemPriceSmall();
                else if(radbtnMedium.isSelected())
                    price = i._prices.getItemPriceMedium();
                else if(radbtnLarge.isSelected())
                    price = i._prices.getItemPriceLarge();
                
                txtboxProdPrice.setText(String.valueOf(price));
            }
        }
        
        
    }
    
    // remove the highlighted row in the Cart Table
    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        cart.RemoveItem();
    }//GEN-LAST:event_btnRemoveItemActionPerformed
    
    
    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        if( !(txtboxProdCode.getText().isEmpty()) || !(txtboxProdCode.getText().isBlank())){ // if input was blank, ignore
            String productSize;
            if(radbtnSmall.isSelected()){
                productSize = "Small";
            }
            else if(radbtnMedium.isSelected()){
                productSize = "Medium";
            }
            else {
                productSize = "Large";
            }
            cart.AddItem(txtboxProdCode.getText(), productSize, (Integer)txtboxProdQuantity.getValue(), Float.parseFloat(txtboxProdPrice.getText()));

        }
    }//GEN-LAST:event_btnAddItemActionPerformed
    
    
    
    // Every time a key is released, this function will search for the ProductCode
    // if results were found, it will display the item name and price in the GUI
    private void txtboxProdCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboxProdCodeKeyReleased
        UpdateItemView();
    }//GEN-LAST:event_txtboxProdCodeKeyReleased
    
    //Initialize and Load all items from items.json and store it in the ProductItems ArrayList 
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       cart = new Cart();
       
       // Read items.json and store it as sa raw string
       String ItemsRaw = "";
        try {
           File myObj = new File("items.json");
           Scanner myReader = new Scanner(myObj);
           while (myReader.hasNextLine()) {
             String data = myReader.nextLine();
             System.out.println(data);
             ItemsRaw = ItemsRaw + data;
           }
           myReader.close();
         } catch (FileNotFoundException e) {
           JOptionPane.showMessageDialog(this,"An error occurred. Cannot load localdatabase " + e.getMessage());
         }
        
        
       String jsonString = ItemsRaw.strip() ;
       JSONObject obj = new JSONObject(jsonString);
       
       // Deserialize JSON and store in ProductItems array as Products object
       JSONArray arr = obj.getJSONArray("Products");
        for (int i = 0; i < arr.length(); i++)
        {
            Products prod = new Products();
            prod.setProductId(arr.getJSONObject(i).getString("ProductCode"));
            prod.setProductName(arr.getJSONObject(i).getString("ItemName"));
            Price price = new Price(arr.getJSONObject(i).getString("ItemPriceSmall"),arr.getJSONObject(i).getString("ItemPriceMedium"),arr.getJSONObject(i).getString("ItemPriceLarge"));
            prod.setPrice(price);
            ProductItems.add(prod);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void txtboxTenderAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboxTenderAmountKeyReleased
        try{
            float change = Float.valueOf(txtboxTenderAmount.getText()) - Float.valueOf(txtboxTotal.getText());
            txtboxChange.setText(String.valueOf(change));
        }catch (java.lang.NumberFormatException NFE){
             System.out.println("Invalid Input.");
        }
    }//GEN-LAST:event_txtboxTenderAmountKeyReleased

    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
        if(tblCart.getRowCount() > 0 && !(txtboxTotal.getText().isBlank()) && !(txtboxTenderAmount.getText().isBlank())){
            txtboxBill.setText("");
            cart.PrintBill();
            
            String filename = java.time.LocalDate.now().toString() + ".txt";
            String curtime = new java.util.Date().toString();
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename, true))) { // save receipt in the log file
                writer.append("\n" +curtime + "\n");
                writer.append(txtboxBill.getText().substring(0, txtboxBill.getText().length() - 43));
            } catch (IOException ex) {
                System.out.println("Unable to save receipt");
                
            }
            btnPrintBill.setEnabled(false);
        }
    }//GEN-LAST:event_btnPrintBillActionPerformed

    private void btnNewTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewTransactionActionPerformed
        txtboxTotal.setText("");
        txtboxTenderAmount.setText("");
        txtboxProdQuantity.setValue(1);
        txtboxProdPrice.setText("");
        txtboxProdName.setText("");
        txtboxProdCode.setText("");
        txtboxChange.setText("");
        txtboxBill.setText("");
        radbtnSmall.setSelected(true);
        DefaultTableModel model = (DefaultTableModel)tblCart.getModel(); 
        int rows = model.getRowCount(); 
        for(int i = rows - 1; i >=0; i--)
        {
           model.removeRow(i); 
        }
        btnPrintBill.setEnabled(true);
    }//GEN-LAST:event_btnNewTransactionActionPerformed

    private void radbtnSmallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnSmallActionPerformed
        UpdateItemView();
    }//GEN-LAST:event_radbtnSmallActionPerformed

    private void radbtnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnMediumActionPerformed
        UpdateItemView();
    }//GEN-LAST:event_radbtnMediumActionPerformed

    private void radbtnLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radbtnLargeActionPerformed
        UpdateItemView();
    }//GEN-LAST:event_radbtnLargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup SizesGroup;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnNewTransaction;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radbtnLarge;
    private javax.swing.JRadioButton radbtnMedium;
    private javax.swing.JRadioButton radbtnSmall;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextArea txtboxBill;
    private javax.swing.JTextField txtboxChange;
    private javax.swing.JTextField txtboxProdCode;
    private javax.swing.JTextField txtboxProdName;
    private javax.swing.JTextField txtboxProdPrice;
    private javax.swing.JSpinner txtboxProdQuantity;
    private javax.swing.JTextField txtboxTenderAmount;
    private javax.swing.JTextField txtboxTotal;
    // End of variables declaration//GEN-END:variables
}
